### ISSUE TITLE
nil values for entity properties

### ISSUE THREAD

**Issue by eRGoon** [Sorix/CloudCore#17] opened 2018-01-04 16:35 UTC
I have some entities with non-optional properties. When I set up Cloudcore to sync my entities, it seems to work fine (but the error might already be there). Adding new Objects to Core Data and saving the changes also works fine.

Now when I delete the App and install it again, I'm waiting for the sync from iCloud to populate my database. However, I sometimes get validation errors from Core Data because the fetched records have nil values on non-optional properties. This seems a bit strange to me, because they should only be synced, if they were saved locally and therefor passed Core Data validation.

**Comment by Sorix** [comment] 2018-01-04 20:39
Please post errors that you see in logs and attach your database model.

**Comment by eRGoon** [comment] 2018-01-04 21:10
<img width="924" alt="bildschirmfoto 2018-01-04 um 22 07 13" src="https://user-images.githubusercontent.com/1208463/34584347-bd243608-f19b-11e7-8968-0743d8594109.png">

That's my database schema. Unfortunately I couldn't reproduce the issue anymore. I'll try and send you the logs but it was a Cocoa Error 1570.

**Comment by Sorix** [comment] 2018-01-07 14:46
Please attach full logs (CloudCore reports entity and attributes where fail did occur) when they will be available and if you can reproduce it.

I'm closing that issue for now because of lack of information and reproduction troubles, please attach additional information here and I will reopen it.

**Closed as completed by Sorix** 2018-01-07 14:46 UTC
